"""Syncing models with database

Revision ID: 12aa00263b7f
Revises: 
Create Date: 2024-11-16 14:56:38.804524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12aa00263b7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_additional_info', sa.Boolean(), nullable=True))
        batch_op.drop_column('farmer_name')
        batch_op.drop_column('farm_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('farmer_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('has_additional_info')

    # ### end Alembic commands ###
