"""Add description column to diseases table

Revision ID: 5ade3b22670c
Revises: 
Create Date: 2024-10-19 16:51:16.550379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ade3b22670c'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('diseases', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
