"""Add Seen culumn to Contact maessage table

Revision ID: 6f0778763def
Revises: 8a666891348e
Create Date: 2024-11-11 08:27:18.363965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0778763def'
down_revision = '8a666891348e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
