"""Add column date joined and publish to team members table

Revision ID: 8a666891348e
Revises: 31f7031d1d1b
Create Date: 2024-11-06 16:29:56.768657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a666891348e'
down_revision = '31f7031d1d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_column('published')
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
