"""Add is_trending column to diseases table

Revision ID: a4674d8c8910
Revises: 5ade3b22670c
Create Date: 2024-10-22 14:35:58.173845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4674d8c8910'
down_revision = '5ade3b22670c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_column('is_trending')

    # ### end Alembic commands ###
