"""Recreate initial migration

Revision ID: b21102741eb9
Revises: 
Create Date: 2024-11-14 12:05:10.742774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21102741eb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_contact_message_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_farmer_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_farmer_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contact_message_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
