"""Initial migration after reset

Revision ID: e916c8132b35
Revises: 
Create Date: 2025-01-14 08:07:08.607825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e916c8132b35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the table to handle unnamed constraints
    op.execute('''
        CREATE TABLE user_notifications_new (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            notification_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            is_read BOOLEAN DEFAULT 0,
            FOREIGN KEY(notification_id) REFERENCES notifications(id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
    ''')
    op.execute('''
        INSERT INTO user_notifications_new (id, notification_id, user_id, is_read)
        SELECT id, notification_id, user_id, is_read
        FROM user_notifications
    ''')
    op.execute('DROP TABLE user_notifications')
    op.execute('ALTER TABLE user_notifications_new RENAME TO user_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        CREATE TABLE user_notifications_old (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            notification_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            is_read BOOLEAN DEFAULT 0,
            FOREIGN KEY(notification_id) REFERENCES notifications(id),
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
    ''')
    op.execute('''
        INSERT INTO user_notifications_old (id, notification_id, user_id, is_read)
        SELECT id, notification_id, user_id, is_read
        FROM user_notifications
    ''')
    op.execute('DROP TABLE user_notifications')
    op.execute('ALTER TABLE user_notifications_old RENAME TO user_notifications')
    # ### end Alembic commands ###
